const assert=require('node:assert/strict');
const {prepareEdgeRoutes,routeControls,routeClearance,createRoutedRibbonPath}=require('../visualization/edge-routing.js');
const node=(domain,x,y,r=20)=>({domain,screenX:x,screenY:y,screenRadius:r});
const a=node('a',100,300),b=node('b',900,300),block=node('block',500,300,65);
const pair={nodeA:a,nodeB:b};
prepareEdgeRoutes([pair],[a,b,block],{width:1000,height:700});
assert.equal(routeClearance(routeControls(a,b,pair.route),[block]),0,'Curve must bypass the middle node with padding');
assert(Math.abs(pair.route.bend)>=0.16);
const path=createRoutedRibbonPath(a,b,pair.route,5,1.55,3.8,false);
const reverse=createRoutedRibbonPath(b,a,pair.route,5,1.55,3.8,true);
assert.notEqual(path,reverse);
assert(!/NaN|Infinity/.test(path+reverse));
const c=node('c',850,340),d=node('d',850,260);
const pairs=[pair,{nodeA:a,nodeB:c},{nodeA:a,nodeB:d}];
prepareEdgeRoutes(pairs,[a,b,c,d,block],{width:1000,height:700});
assert.equal(new Set(pairs.map(pair=>pair.route.startAngle)).size,3,'Hub ports must fan out');
const cached=JSON.stringify(pair.route);
a.renderX=102;
assert.notEqual(createRoutedRibbonPath(a,b,pair.route,5,1.55,3.8,false),path);
assert.equal(JSON.stringify(pair.route),cached,'Motion must reuse the routing recipe');
assert.equal(createRoutedRibbonPath(a,node('overlap',105,300),pair.route,5,1.55,0,false),'');
console.log('PASS routes: padded obstacle avoidance, hub fan-out, directional paths, cached animation, overlap');
